### ISSUE TITLE
Not working

### ISSUE THREAD

**Issue by UltiRequiem** [uetchy/create-create-app#31]
```
Creating a new package in /home/z/disk/repos/packages/npm/create-npm-card/hehe.

Parse error on line 937:
...ediately following "\{{" ([@dmarcotte](h
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'


Error: Parse error on line 937:
...ediately following "\{{" ([@dmarcotte](h
-----------------------^
Expecting 'CLOSE_RAW_BLOCK', 'CLOSE', 'CLOSE_UNESCAPED', 'OPEN_SEXPR', 'CLOSE_SEXPR', 'ID', 'OPEN_BLOCK_PARAMS', 'STRING', 'NUMBER', 'BOOLEAN', 'UNDEFINED', 'NULL', 'DATA', got 'INVALID'
    at Parser.parseError (/home/z/disk/repos/packages/npm/create-npm-card/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:267:19)
    at Parser.parse (/home/z/disk/repos/packages/npm/create-npm-card/node_modules/handlebars/dist/cjs/handlebars/compiler/parser.js:336:30)
    at parseWithoutProcessing (/home/z/disk/repos/packages/npm/create-npm-card/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:46:33)
    at HandlebarsEnvironment.parse (/home/z/disk/repos/packages/npm/create-npm-card/node_modules/handlebars/dist/cjs/handlebars/compiler/base.js:52:13)
    at compileInput (/home/z/disk/repos/packages/npm/create-npm-card/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:508:19)
    at ret (/home/z/disk/repos/packages/npm/create-npm-card/node_modules/handlebars/dist/cjs/handlebars/compiler/compiler.js:517:18)
    at T (/home/z/disk/repos/packages/npm/create-npm-card/node_modules/create-create-app/lib/chunk.PN6R6NCW.js:1:2328)
    at L (/home/z/disk/repos/packages/npm/create-npm-card/node_modules/create-create-app/lib/chunk.PN6R6NCW.js:1:2836)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async Ie (/home/z/disk/repos/packages/npm/create-npm-card/node_modules/create-create-app/lib/chunk.PN6R6NCW.js:3:4)


# Environment
- create-create-app: 7.1.0
- System > OS: Linux 5.16 Arch Linux
- Binaries > Node: 17.7.2 - /bin/node
```

Steps to reproduce

1) Clone https://github.com/UltiRequiem/create-npm-card
2) npm run build
3) node dist/cli.js

**Comment by UltiRequiem** [comment]
Despite these errors the build is successful.

**Comment by uetchy** [comment]
Couldn't reproduce the error. Did you fix this already?

**Comment by UltiRequiem** [comment]
Yes, not sure what was causing it.
